### ISSUE TITLE
WATERSS report and AOI type

### ISSUE THREAD

**Issue by wmbeers** [wmbeers/cmv-app#61]
Lex has added a new value to the LU_PROJECT_TYPE lookup table for supporting AOI analysis for WATERSS.

PK_PROJECT_TYPE: 18
PROJECT_TYPE: WATERSS	
Description: Watershed Approach to Evaluate Regional Stormwater Solutions

We don't read from this table, so it needs to be added to the projectTypes array in AoiEditor.js

See also Issue #55 for enhancement to load thematic maps, how we're implementing the WATERSS maps.

**Comment by wmbeers** [comment]
Changes made under https://github.com/wmbeers/cmv-app/tree/WATERSS branch.

**Comment by wmbeers** [comment]
Extending this to include support for requesting and viewing report generation progress for the new WATERSS report.

Tied to EST code changes under Bug 6109 - Provide support in the UI and database for requesting a WATERSS report on an AOI and tracking the status of generating the report

**Comment by mikekonikoff** [comment]
Please enable this option on dev and stage

**Comment by wmbeers** [comment]
> Please enable this option on dev and stage

Working on dev. DB changes needed for stage migration.

**Comment by wmbeers** [comment]
Note: Bug #6109 is merging to pre-prod this weekend for back end support and simplify deployment of HCM related bugs and AOI improvements, but we're holding off on displaying WATERSS report option in AOI UI for now.

**Comment by wmbeers** [comment]
6109 closed with pull request 103/104
